/**
 * ATProto PDS store for GitHub Sponsors data.
 *
 * Each sponsorship event is stored as a separate record under:
 *   uk.ewancroft.github.sponsor
 *
 * rkeys are TIDs generated by @ewanc26/tid — one record per event.
 * The aggregated GitHubSponsor view is built at read time by replaying
 * events in chronological order per sponsor.
 *
 * Reads are public (no auth). Writes use an app password.
 *
 * Required environment variables:
 *   ATPROTO_DID           — your DID, e.g. did:plc:abc123
 *   ATPROTO_APP_PASSWORD  — an app password from your PDS settings
 */

import { AtpAgent } from '@atproto/api';
import { generateTID, decodeTid } from "@ewanc26/tid";
import type { GitHubSponsor, GitHubSponsorshipAction } from './github-types.js';

const COLLECTION = 'uk.ewancroft.support.github';

const ACTIVE_ACTIONS: GitHubSponsorshipAction[] = ['created', 'tier_changed'];
const INACTIVE_ACTIONS: GitHubSponsorshipAction[] = ['cancelled'];

/** The shape of a raw record stored in the PDS. */
export interface GitHubSponsorEventRecord {
	login: string;
	name?: string;
	action: GitHubSponsorshipAction;
	tierName: string;
	monthlyUsd: number;
}

/** A single sponsor event as returned by fetchSponsorEvents. */
export interface GitHubSponsorEvent {
	rkey: string;
	login: string;
	name?: string;
	action: GitHubSponsorshipAction;
	tierName: string;
	monthlyUsd: number;
	date: Date;
}

const VALID_ACTIONS: GitHubSponsorshipAction[] = [
	'created',
	'cancelled',
	'edited',
	'tier_changed',
	'pending_cancellation',
	'pending_tier_change'
];

/**
 * Validate a raw PDS record value before trusting it as a GitHubSponsorEventRecord.
 * PDS records are untyped JSON blobs at the SDK level — a malformed or
 * tampered record must not silently propagate undefined fields into the
 * aggregated sponsor list.
 */
function parseGitHubSponsorEventRecord(value: unknown): GitHubSponsorEventRecord | null {
	if (typeof value !== 'object' || value === null) return null;
	const v = value as Record<string, unknown>;

	if (typeof v.login !== 'string' || v.login.length === 0) return null;
	if (typeof v.action !== 'string' || !VALID_ACTIONS.includes(v.action as GitHubSponsorshipAction)) return null;
	if (typeof v.tierName !== 'string') return null;
	if (typeof v.monthlyUsd !== 'number' || !Number.isFinite(v.monthlyUsd)) return null;
	if ('name' in v && v.name !== undefined && typeof v.name !== 'string') return null;

	return {
		login: v.login,
		name: typeof v.name === 'string' ? v.name : undefined,
		action: v.action as GitHubSponsorshipAction,
		tierName: v.tierName,
		monthlyUsd: v.monthlyUsd
	};
}

function requireEnv(key: string): string {
	const val = process.env[key];
	if (!val) throw new Error(`Missing required environment variable: ${key}`);
	return val;
}

async function resolvePdsUrl(did: string): Promise<string> {
	const res = await fetch(
		`https://slingshot.microcosm.blue/xrpc/com.bad-example.identity.resolveMiniDoc?identifier=${encodeURIComponent(did)}`
	);
	if (!res.ok) throw new Error(`Failed to resolve PDS for ${did}: ${res.status}`);
	const data = (await res.json()) as { pds?: string };
	if (!data.pds) throw new Error(`No PDS found in identity document for ${did}`);
	return data.pds;
}

async function authedAgent(): Promise<{ agent: AtpAgent; did: string }> {
	const did = requireEnv('ATPROTO_DID');
	const password = requireEnv('ATPROTO_APP_PASSWORD');
	const pdsUrl = await resolvePdsUrl(did);
	const agent = new AtpAgent({ service: pdsUrl });
	await agent.login({ identifier: did, password });
	return { agent, did };
}

/**
 * Fetch all GitHub sponsor events as a chronological timeline.
 * Mirrors fetchEvents() from events.ts — returns one entry per PDS record,
 * sorted most-recent-first.
 * No auth required — collection is publicly readable.
 */
export async function fetchSponsorEvents(did: string): Promise<GitHubSponsorEvent[]> {
	const pdsUrl = await resolvePdsUrl(did);
	const agent = new AtpAgent({ service: pdsUrl });

	const events: GitHubSponsorEvent[] = [];
	let cursor: string | undefined;

	do {
		const res = await agent.com.atproto.repo.listRecords({
			repo: did,
			collection: COLLECTION,
			limit: 100,
			cursor
		});

		for (const record of res.data.records) {
			const value = parseGitHubSponsorEventRecord(record.value);
			if (!value) continue;
			const rkey = record.uri.split('/').pop() ?? '';
			let date: Date;
			try {
				date = decodeTid(rkey).date;
			} catch {
				date = new Date(0);
			}
			events.push({
				rkey,
				login: value.login,
				name: value.name,
				action: value.action,
				tierName: value.tierName,
				monthlyUsd: value.monthlyUsd,
				date
			});
		}

		cursor = res.data.cursor;
	} while (cursor);

	return events.sort((a, b) => b.date.getTime() - a.date.getTime());
}

/**
 * Read all sponsor event records from the PDS and aggregate into GitHubSponsor objects.
 * Events are replayed in rkey (TID) order so the last-known state wins per sponsor.
 * No auth required — collection is publicly readable.
 */
export async function readSponsors(): Promise<GitHubSponsor[]> {
	const did = requireEnv('ATPROTO_DID');
	const pdsUrl = await resolvePdsUrl(did);
	const agent = new AtpAgent({ service: pdsUrl });

	const events: Array<{ rkey: string; record: GitHubSponsorEventRecord }> = [];
	let cursor: string | undefined;

	do {
		const res = await agent.com.atproto.repo.listRecords({
			repo: did,
			collection: COLLECTION,
			limit: 100,
			cursor
		});

		for (const record of res.data.records) {
			const value = parseGitHubSponsorEventRecord(record.value);
			if (!value) continue;
			const rkey = record.uri.split('/').pop() ?? '';
			events.push({ rkey, record: value });
		}

		cursor = res.data.cursor;
	} while (cursor);

	events.sort((a, b) => (a.rkey < b.rkey ? -1 : 1));

	return aggregateEvents(events.map((e) => e.record));
}

function aggregateEvents(events: GitHubSponsorEventRecord[]): GitHubSponsor[] {
	const map = new Map<string, GitHubSponsor>();

	for (const event of events) {
		const existing = map.get(event.login);
		const isActive = ACTIVE_ACTIONS.includes(event.action)
			? true
			: INACTIVE_ACTIONS.includes(event.action)
				? false
				: (existing?.isActive ?? true);

		map.set(event.login, {
			login: event.login,
			name: event.name ?? existing?.name,
			tierName: event.tierName,
			monthlyUsd: event.monthlyUsd,
			isActive
		});
	}

	return Array.from(map.values());
}

/**
 * Write a single GitHub Sponsors event as a new PDS record.
 * rkey is a TID generated from the event timestamp.
 */
export async function appendSponsorEvent(
	login: string,
	name: string | null,
	action: GitHubSponsorshipAction,
	tierName: string,
	monthlyUsd: number,
	timestamp: string
): Promise<void> {
	const { agent, did } = await authedAgent();

	const record: GitHubSponsorEventRecord = {
		login,
		...(name ? { name } : {}),
		action,
		tierName,
		monthlyUsd
	};

	const ts = timestamp.endsWith('Z') ? timestamp : timestamp + 'Z';

	await agent.com.atproto.repo.putRecord({
		repo: did,
		collection: COLLECTION,
		rkey: generateTID(ts),
		record: record as unknown as { [x: string]: unknown }
	});
}
