/**
 * ATProto PDS store for Ko-fi supporter data.
 *
 * Each Ko-fi event is stored as a separate record under:
 *   uk.ewancroft.kofi.supporter
 *
 * rkeys are TIDs generated by @ewanc26/tid — one record per event.
 * The aggregated KofiSupporter view (deduped by name) is built at read time.
 *
 * Reads are public (no auth). Writes use an app password.
 *
 * Required environment variables:
 *   ATPROTO_DID           — your DID, e.g. did:plc:abc123
 *   ATPROTO_PDS_URL       — your PDS URL, e.g. https://pds.ewancroft.uk
 *   ATPROTO_APP_PASSWORD  — an app password from your PDS settings
 */

import { AtpAgent } from '@atproto/api';
import { generateTID } from '@ewanc26/tid';
import type { KofiSupporter, KofiEventType } from './types.js';

const COLLECTION = 'uk.ewancroft.kofi.supporter';

/** The shape of a raw record stored in the PDS. */
export interface KofiEventRecord {
	name: string;
	type: KofiEventType;
	tier?: string;
}

function requireEnv(key: string): string {
	const val = process.env[key];
	if (!val) throw new Error(`Missing required environment variable: ${key}`);
	return val;
}

function dedupe<T>(arr: T[], extra: T): T[] {
	return Array.from(new Set([...arr, extra]));
}

/** Authenticated agent for write operations. */
async function authedAgent(): Promise<{ agent: AtpAgent; did: string }> {
	const did = requireEnv('ATPROTO_DID');
	const pdsUrl = requireEnv('ATPROTO_PDS_URL');
	const password = requireEnv('ATPROTO_APP_PASSWORD');

	const agent = new AtpAgent({ service: pdsUrl });
	await agent.login({ identifier: did, password });
	return { agent, did };
}

/**
 * Read all event records from the PDS and aggregate into KofiSupporter objects.
 * No auth required — collection is publicly readable.
 */
export async function readStore(): Promise<KofiSupporter[]> {
	const did = requireEnv('ATPROTO_DID');
	const pdsUrl = requireEnv('ATPROTO_PDS_URL');

	const agent = new AtpAgent({ service: pdsUrl });

	const events: KofiEventRecord[] = [];
	let cursor: string | undefined;

	do {
		const res = await agent.com.atproto.repo.listRecords({
			repo: did,
			collection: COLLECTION,
			limit: 100,
			cursor
		});

		for (const record of res.data.records) {
			events.push(record.value as unknown as KofiEventRecord);
		}

		cursor = res.data.cursor;
	} while (cursor);

	return aggregateEvents(events);
}

/** Aggregate raw event records into deduplicated KofiSupporter objects. */
function aggregateEvents(events: KofiEventRecord[]): KofiSupporter[] {
	const map = new Map<string, KofiSupporter>();

	for (const event of events) {
		const existing = map.get(event.name);
		map.set(event.name, {
			name: event.name,
			types: dedupe(existing?.types ?? [], event.type),
			tiers: event.tier
				? dedupe(existing?.tiers ?? [], event.tier)
				: (existing?.tiers ?? [])
		});
	}

	return Array.from(map.values());
}

/**
 * Write a single Ko-fi event as a new record.
 * rkey is a TID generated at call time.
 */
export async function appendEvent(
	name: string,
	type: KofiEventType,
	tier: string | null,
	timestamp: string
): Promise<void> {
	const { agent, did } = await authedAgent();

	const record: KofiEventRecord = {
		name,
		type,
		...(tier ? { tier } : {})
	};

	await agent.com.atproto.repo.putRecord({
		repo: did,
		collection: COLLECTION,
		rkey: generateTID(timestamp),
		record: record as unknown as { [x: string]: unknown }
	});
}
