/**
 * ATProto PDS store for Ko-fi supporter data.
 *
 * Each Ko-fi event is stored as a separate record under:
 *   uk.ewancroft.support.kofi
 *
 * rkeys are TIDs generated by @ewanc26/tid — one record per event.
 * The aggregated KofiSupporter view (deduped by name) is built at read time.
 *
 * Reads are public (no auth). Writes use an app password.
 *
 * Required environment variables:
 *   ATPROTO_DID           — your DID, e.g. did:plc:abc123
 *   ATPROTO_APP_PASSWORD  — an app password from your PDS settings
 *
 * The PDS URL is resolved automatically from the DID via Slingshot.
 */

import { Client } from '@atproto/lex'
import { PasswordSession } from '@atproto/lex-password-session'
import { generateTID } from "@ewanc26/tid";
import type { KofiSupporter, KofiEventType } from './types.js';
import { com } from '@bsky/sdk/lexicons'

const COLLECTION = 'uk.ewancroft.support.kofi';

/** The shape of a raw record stored in the PDS. */
export interface KofiEventRecord {
	name: string;
	type: KofiEventType;
	tier?: string;
	isSubscriptionPayment?: true;
	isFirstSubscriptionPayment?: true;
	shopItems?: string[];
}

function requireEnv(key: string): string {
	const val = process.env[key];
	if (!val) throw new Error(`Missing required environment variable: ${key}`);
	return val;
}

function dedupe<T>(arr: T[], extra: T): T[] {
	return Array.from(new Set([...arr, extra]));
}

/** Resolve the PDS URL for a DID via the AT Protocol identity endpoint. */
async function resolvePdsUrl(did: string): Promise<string> {
	const res = await fetch(
		`https://slingshot.microcosm.blue/xrpc/com.bad-example.identity.resolveMiniDoc?identifier=${encodeURIComponent(did)}`
	);
	if (!res.ok) throw new Error(`Failed to resolve PDS for ${did}: ${res.status}`);
	const data = await res.json() as { pds?: string };
	if (!data.pds) throw new Error(`No PDS found in identity document for ${did}`);
	return data.pds;
}

/** Authenticated client for write operations. */
async function authedClient(): Promise<{ client: Client; did: string }> {
  const did = requireEnv('ATPROTO_DID');
  const password = requireEnv('ATPROTO_APP_PASSWORD');

  const pdsUrl = await resolvePdsUrl(did);
  const session = await PasswordSession.login({
    service: pdsUrl,
    identifier: did,
    password,
  });
  const client = new Client(session, { service: pdsUrl as any });
  return { client, did };
}

/**
 * Read all event records from the PDS and aggregate into KofiSupporter objects.
 * No auth required — collection is publicly readable.
 */
export async function readStore(): Promise<KofiSupporter[]> {
	const did = requireEnv('ATPROTO_DID');
	const pdsUrl = await resolvePdsUrl(did);

	const client = new Client(pdsUrl);

	const events: KofiEventRecord[] = [];
	let cursor: string | undefined;

	do {
		const res = await client.call(com.atproto.repo.listRecords, {
			repo: did as any,
			collection: COLLECTION,
			limit: 100,
			cursor
		});

		for (const record of res.records) {
			events.push(record.value as any);
		}

		cursor = res.cursor;
	} while (cursor);

	return aggregateEvents(events);
}

/** Aggregate raw event records into deduplicated KofiSupporter objects. */
function aggregateEvents(events: KofiEventRecord[]): KofiSupporter[] {
	const map = new Map<string, KofiSupporter>();

	for (const event of events) {
		const existing = map.get(event.name);
		map.set(event.name, {
			name: event.name,
			types: dedupe(existing?.types ?? [], event.type),
			tiers: event.tier
				? dedupe(existing?.tiers ?? [], event.tier)
				: (existing?.tiers ?? [])
		});
	}

	return Array.from(map.values());
}

/**
 * Write a single Ko-fi event as a new record.
 * rkey is a TID generated from the event timestamp.
 * Timestamp is normalised to UTC before encoding.
 */
export async function appendEvent(
	name: string,
	type: KofiEventType,
	tier: string | null,
	timestamp: string,
	opts?: {
		isSubscriptionPayment?: boolean;
		isFirstSubscriptionPayment?: boolean;
		shopItems?: string[];
	}
): Promise<void> {
	const { client, did } = await authedClient();

	// Ko-fi timestamps have no timezone; normalise to UTC
	const ts = timestamp.endsWith('Z') ? timestamp : timestamp + 'Z';

	const record: KofiEventRecord = {
		name,
		type,
		...(tier ? { tier } : {}),
		...(opts?.isSubscriptionPayment ? { isSubscriptionPayment: true as const } : {}),
		...(opts?.isFirstSubscriptionPayment ? { isFirstSubscriptionPayment: true as const } : {}),
		...(opts?.shopItems?.length ? { shopItems: opts.shopItems } : {})
	};

	await client.call(com.atproto.repo.putRecord.main as any, {
		repo: did as any,
		collection: COLLECTION,
		rkey: generateTID(ts),
		record: record as any
	});
}
