/**
 * Prebuild script: inlines Inter font files as base64 into src/fonts-base64.ts
 * so the distributed package works in serverless environments (Vercel etc.)
 * without relying on filesystem access to node_modules.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const bold = await readFile(resolve(root, 'fonts/Inter-Bold.ttf'))
const regular = await readFile(resolve(root, 'fonts/Inter-Regular.ttf'))

const output = `/**
 * Auto-generated by scripts/prebuild.mjs — do not edit.
 * Inter font files inlined as base64 for serverless compatibility.
 */

export const INTER_BOLD_B64 = '${bold.toString('base64')}'
export const INTER_REGULAR_B64 = '${regular.toString('base64')}'
`

await writeFile(resolve(root, 'src/fonts-base64.ts'), output)
console.log('fonts-base64.ts written')
